### PR TITLE
move main.go to be within the cmd directory structure and push all subcommands down one layer

### PR DESCRIPTION
**Pull request by komish**
This PR is in preparation for exposing code at the top layer of the directory structure to be library code. We have to move main.go into `cmd` so that the import path can be correct for library code, and also probably should anyway as it doesn't hurt anything.

Signed-off-by: Jose R. Gonzalez <jose@flutes.dev>

### CODE REVIEW

**Review by acornett21 — COMMENTED** [review]
Can't `main` live in `/cmd` without having a sub folder? cmd/prflight/cmd seems like a weird package path.

**Comment by acornett21** [comment]
> Can't `main` live in `/cmd` without having a sub folder? cmd/prflight/cmd seems like a weird package path.

Looking at a few other repos, it looks like this pattern is actually common.

**Comment by komish** [comment]
> Can't `main` live in `/cmd` without having a sub folder? cmd/prflight/cmd seems like a weird package path.

I don’t think so. The package for the entry point must be main, but the cobra commands probably shouldn’t live in the main package.

**Comment by tkrishtop** [comment]
hi @komish sorry for the failed job, we got an issue with the folder permissions in Dallas, it is now fixed

**Review by sebrandon1 — APPROVED** [review]

**Review by bcrochet — APPROVED** [review]
/lgtm

Awesome that the changes were pretty limited and just a 'git mv' in most cases.

**Review by skattoju4 — APPROVED** [review]
/lgtm

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
