### PR TITLE
Update Go to v1.19.3

### PR DESCRIPTION
**Pull request by sebrandon1**
https://groups.google.com/g/golang-announce/c/mbHY1UY3BaM?pli=1

### CODE REVIEW

**Review by acornett21 — COMMENTED** [review]
Would we also want to change our Dockerfile as well to point to the latest golang builder image?

**Review by bcrochet — APPROVED** [review]
/lgtm

**Comment by acornett21** [comment]
> Would we also want to change our Dockerfile as well to point to the latest golang builder image?

It looks like golang always points the major version to the latest minior version, so no change is needed in the docker file.

```
v1.19 -> v1.19.3 all point to the same sha
```

**Pull request merged**
