### PR TITLE
updating k8s dependencies, since dependabot can't make these changes

### PR DESCRIPTION
**Pull request by acornett21**
- These changes need to go together, and dependabot can't make them all at once.
- Updated to go 1.20

### CODE REVIEW

**Comment by komish** [comment]
@acornett21 What's holding back bumping the Golang version here?

**Review by komish — APPROVED** [review]
/lgtm

**Comment by acornett21** [comment]
> @acornett21 What's holding back bumping the Golang version here?

When I initially looked at this, I thought we were going to be _forced_ to go to `1.20`, but we aren't. This PR could also move everything (mod, docker, ci) to `1.20` if that's what you and @bcrochet prefer, or we can have `1.20` be a follow up PR.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
