### PR TITLE
[do not merge, testing] Retrieve error message from sub.Status.Conditions

### LINKED ISSUE #769: provide more accurate details of DeployableByOLM failure in preflight.log
## Is your feature request related to a problem? Please describe.
Currently when preflight tool is trying to install operator within `DeployableByOLM` test, if installation fails preflight logs don't provide enough information for troubleshooting. It gets messages only from installed CSV - please check the code https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/786f9be6f3e0d0245755cf68e29df5865025b871/certification/internal/policy/operator/deployable_by_olm.go#L497-L517

Unfortunately that is not enough sometimes, in addition to those CSV messages it would be great to log subscription `status.Conditions` field details as well.

Here is example of that section of the subscription:
```
  Conditions:
    Last Transition Time:   2022-08-11T03:33:19Z
    Message:                all available catalogsources are healthy
    Reason:                 AllCatalogSourcesHealthy
    Status:                 False
    Type:                   CatalogSourcesUnhealthy
    Last Transition Time:   2022-08-11T03:34:54Z
    Message:                error updating service: my-long-prefix-that-cause-failure-controller-manager-metrics-service: Service "my-long-prefix-that-cause-failure-controller-manager-metrics-service" is invalid: metadata.name: Invalid value: "my-long-prefix-that-cause-failure-controller-manager-metrics-service": must be no more than 63 characters
    Reason:                 InstallComponentFailed
    Status:                 True
    Type:                   InstallPlanFailed
```

To be able to catch this we need to monitor subscription manually during the test (or during manual operator deployment) and capture status of the subscription.

## Describe the solution you'd like.
in addition to those CSV messages it would be great to log subscription `status.Conditions` field details as well.

## Describe alternatives you've considered.
To be able to catch this we need to monitor subscription manually during the test (or during manual operator deployment) and capture status of the subscription.

## Additional context.
N/A

### PR DESCRIPTION
**Pull request by tkrishtop**
Signed-off-by: Tatiana Krishtop <tkrishto@redhat.com>

Fix #769

### CODE REVIEW

**Comment by bcrochet** [comment]
Ok to close this?

**Comment by tkrishtop** [comment]
@bcrochet sorry I forgot to answer, yes, I agree with your comment on the issue. We discussed with Marat and devs on the partner side and moved to a more strict automated application testing before running Preflight.  

Tony from my team will use this PR for some testing today, and then we can close it.

**Comment by tonyskapunk** [comment]
I've completed the testing, this can be closed @bcrochet 

Thanks

**Comment by acornett21** [comment]
Closed based on the discussion. Thanks all!

**Pull request closed without merging**
