### PR TITLE
list only files greater than minLicenseSize

### LINKED ISSUE #161: License check should validate file size
Not only should preflight check for file or files in /licenses it should check that those files are not zero length, which would be a useless license.

### PR DESCRIPTION
**Pull request by skattoju**
fixes #161 
- now checking if the license folder contains files larger than 1 byte
- using find instead of ls

### CODE REVIEW

**Review by samira-barouti — APPROVED** [review]
/lgtm
Out of curiosity: is this how this check is being done in the Ansible playbooks?

**Comment by skattoju** [comment]
not sure could not find the ansible version of the check
https://github.com/redhat-openshift-ecosystem/operator-test-playbooks

**Comment by samira-barouti** [comment]
@skattoju IMO we better check for a keyword (such as License and ignoring the cases) in the files to ensure the files do not contain random contents.

**Comment by skattoju** [comment]
I think we said we don't want to get into verifying the contents as this is
enforced by legal agreements. They could always create a dummy license
with the word "license" right ?

**Comment by bcrochet** [comment]
> I think we said we don't want to get into verifying the contents as this is enforced by legal agreements. They could always create a dummy license with the word "license" right ?

That is correct. We are at least checking that they put *something* in a file in /licenses. We just want to protect someone touching a file in /licenses, trying to get this to pass, then to forget to go back and put something in.

**Pull request merged**
