### PR TITLE
updating check container check url in all checks

### PR DESCRIPTION
**Pull request by acornett21**
- Fixes: #519 
- Updating all url's in all checks to point to cert policy docs

Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Review by bcrochet — CHANGES_REQUESTED** [review]
Can we put that in a constant somewhere?

**Comment by jomkz** [comment]
> Can we put that in a constant somewhere?

+1 perhaps use that as the default for in the future when a check specific URL/anchor isn’t available

**Comment by acornett21** [comment]
> should we deprecate one of those since both point to the same thing ?

There are different URL's for someone of the `check operator` check. Also, these values get sent to pyxis for the partner to view, so to not break anything in pyxis or connect, it's best that we keep both.

**Comment by acornett21** [comment]
@bcrochet Moved this to package level constant.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by jomkz — APPROVED** [review]

**Pull request merged**
