### PR TITLE
Move to Operator-SDK 1.29.0 containing fix for disconnected env

### PR DESCRIPTION
**Pull request by tkrishtop**
build-depends: 28500

### CODE REVIEW

**Comment by tkrishtop** [comment]
Hello team, I put the PR in DNM mode while debugging what is wrong with the integration. For the moment, it looks like a mirroring issue on our side.

**Comment by tkrishtop** [comment]
Hello team, thank you for the patience, the mirroring is fixed, ready for review.

**Review by acornett21 — APPROVED** [review]

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
