### PR TITLE
Validation for Operator Bundle PackageName Uniqueness

### LINKED ISSUE #34: [Check] Operator Package Name Uniqueness
This check will require an API from the backend teams.  The API should accept a package name and return true if the name is unique (no other packages have that name) or false if the name is a duplicate of an existing package name in any of the catalogs

Need to work with the backend teams (CVP?) to have them create the API for us.

### PR DESCRIPTION
**Pull request by rocrisp**
Fixes #34

### CODE REVIEW

**Comment by komish** [comment]
@rocrisp can you add a bit of context to the comments here on exactly how you solved the issue?

**Comment by rocrisp** [comment]
This check validates the bundle package name, ex argocd-operator against the Red Hat catalog registry, 
https://catalog.redhat.com/api/containers/v1/operators/packages.
We get the argocd-operator from the contents of image.
The contents are extracted from operator-sdk scorecard currently which is not favorable. 
The good news is that Brad is working on a podman unshare which I will consume.
With that said, let's put this PR on hold until such functionality can be consumed.

**Comment by rocrisp** [comment]
Closing without merge. Jose is going to break it down and add tests.

**Comment by komish** [comment]
@rocrisp is tasked with some other things, I'll make some adjustments on her branch and re-submit as a PR with her commits included! Thanks @rocrisp

**Pull request closed without merging**
