### PR TITLE
Move to the latest operator-sdk 1.26.0

### PR DESCRIPTION
**Pull request by tkrishtop**
Signed-off-by: Tatiana Krishtop <tkrishto@redhat.com>

That should allow for getting more detailed error messages when the scorecard-sdk times out.

### CODE REVIEW

**Comment by tkrishtop** [comment]
> Regular contributors should [join the org](https://github.com/orgs/redhat-openshift-ecosystem/people) to skip this step.

Hi @acornett21, do you know who to ping to join?

**Comment by acornett21** [comment]
@tkrishtop I'm not sure who owns the `redhat-openshift-ecosystem` org. 

@jomkz Do you happen to know?

**Comment by bcrochet** [comment]
Would love to wait for this to land: https://github.com/operator-framework/operator-sdk/pull/6187

But understand if there is a more pressing need to bump this.

@tkrishtop

**Comment by tkrishtop** [comment]
> Would love to wait for this to land: [operator-framework/operator-sdk#6187](https://github.com/operator-framework/operator-sdk/pull/6187)
> 
> But understand if there is a more pressing need to bump this.
> 
> @tkrishtop

Oh, 4.12 security labels, [I had to add them as well to run the preflight check on 4.12](https://softwarefactory-project.io/r/c/dci-openshift-app-agent/+/26539), it's nice to know that the proper solution is coming.

I'm not sure how long we'll have to wait for #6187 to be merged. The discussion has been ongoing for 2 months already. I'd prefer to merge 1.26.0 and move forward with these annoying scorecard timeouts - they happen all the time when you run 20 `preflight check operator` in one job. I tested my change on the latest GA for 4.11, and everything looks safe.

**Comment by bcrochet** [comment]
> > Would love to wait for this to land: [operator-framework/operator-sdk#6187](https://github.com/operator-framework/operator-sdk/pull/6187)
> > But understand if there is a more pressing need to bump this.
> > @tkrishtop
> 
> Oh, 4.12 security labels, [I had to add them as well to run the preflight check on 4.12](https://softwarefactory-project.io/r/c/dci-openshift-app-agent/+/26539), it's nice to know that the proper solution is coming.
> 
> @bcrochet thanks for checking the PR! I'm not sure how long we'll have to wait for #6187 to be merged. The discussion has been ongoing for 2 months already. I'd prefer to merge 1.26.0 and move forward with these annoying scorecard timeouts - they happen all the time when you run 20 `preflight check operator` in one job. I tested my change on the latest GA for 4.11, and everything looks safe.

Fair enough. 

/lgtm
/approve

**Review by acornett21 — APPROVED** [review]

**Pull request merged**
