### PR TITLE
updating go to 1.21

### PR DESCRIPTION
**Pull request by acornett21**
- updating to go 1.21
- updating to latest `15` series of controller runtime
- updating to latest `27` series of k8's libraries

This will resolve `rapid-rest` CVE issue(s).

### CODE REVIEW

**Review by komish — APPROVED** [review]
/lgtm

**Comment by acornett21** [comment]
Put this PR on hold, since I don't think there is a go `1.21` image for our CI yet.

**Comment by acornett21** [comment]
Removing hold on this PR since fixing the CVE's are more important then waiting on prow to have an updated golang image.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
