### PR TITLE
fix(engine): close file when untar

### PR DESCRIPTION
**Pull request by nikpivkin**

### CODE REVIEW

**Comment by bcrochet** [comment]
@nikpivkin Please add a test for this.

**Comment by nikpivkin** [comment]
@bcrochet What's the test supposed to check? I just added file closing.

**Comment by bcrochet** [comment]
> @bcrochet What's the test supposed to check? I just added file closing.

Fair enough. Thanks for the submission.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by acornett21 — APPROVED** [review]

**Pull request merged**
