### PR TITLE
add ocp 4.16 / k8s 1.29 to ocp to k8s conversion map

### PR DESCRIPTION
**Pull request by acornett21**
- Adding the next version of OCP to the conversion map in the bundle code.

### CODE REVIEW

**Comment by acornett21** [comment]
> from change #1130:
> 
> * FAILURE https://www.distributed-ci.io/jobs/d165d64d-e7a1-45b1-9716-331dc1e9b158/jobStates

This isn't due to any code change, but due to the fact that `opm` is only built on/for RHEL9 so there is a mismatch in glibc versions.

**Review by komish — APPROVED** [review]
/lgtm

**Comment by tonyskapunk** [comment]
check workload preflight-green

**Comment by tonyskapunk** [comment]
check workload preflight-green

**Pull request merged**
