### PR TITLE
Bug fixes from main

### PR DESCRIPTION
**Pull request by bcrochet**
Cherry-picks from main

Signed-off-by: Brad P. Crochet <brad@redhat.com>

### CODE REVIEW

**Comment by bcrochet** [comment]
> error in check dallas: unable to rebase PR 594 from redhat-openshift-ecosystem/openshift-preflight

@tkrishtop You'll probably need to account for other branches.

**Comment by fredericlepied** [comment]
> > error in check dallas: unable to rebase PR 594 from redhat-openshift-ecosystem/openshift-preflight
> 
> @tkrishtop You'll probably need to account for other branches.

Which other branches should we take into account?

**Comment by bcrochet** [comment]
> > > error in check dallas: unable to rebase PR 594 from redhat-openshift-ecosystem/openshift-preflight
> > 
> > 
> > @tkrishtop You'll probably need to account for other branches.
> 
> Which other branches should we take into account?
For instance, this PR is based on 'release-1.1', which I assume is the reason that the dcibot failed.

**Comment by fredericlepied** [comment]
> > > > error in check dallas: unable to rebase PR 594 from redhat-openshift-ecosystem/openshift-preflight
> > > 
> > > 
> > > @tkrishtop You'll probably need to account for other branches.
> > 
> > 
> > Which other branches should we take into account?
> > For instance, this PR is based on 'release-1.1', which I assume is the reason that the dcibot failed.

ok I fixed the code to be able to rebase from the base branch. But now it seems, there is also a conflict with the release-1.1 branch...

**Comment by fredericlepied** [comment]
> > > > > error in check dallas: unable to rebase PR 594 from redhat-openshift-ecosystem/openshift-preflight
> > > > 
> > > > 
> > > > @tkrishtop You'll probably need to account for other branches.
> > > 
> > > 
> > > Which other branches should we take into account?
> > > For instance, this PR is based on 'release-1.1', which I assume is the reason that the dcibot failed.
> 
> ok I fixed the code to be able to rebase from the base branch. But now it seems, there is also a conflict with the release-1.1 branch...

The code to rebase was not correct. So it seems, everything is fine now.

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
