### PR TITLE
Add recipe for check container with the config file

### LINKED ISSUE #692: [Security fix] Add pyxis-api-token-path for those who don't want to disclose the token during the Preflight run
## Is your feature request related to a problem? Please describe.
During the `preflight check container` run with the `--submit` option, the `pyxis-api-token` is displayed in the console. That exposes the token in the history search, and in the logs of different CI tools.

## Describe the solution you'd like.
It would be nice to deal with the Pyxis token the same way as we deal with the docker config: instead of providing the token itself, provide a path to the file that contains the token.  

To keep backward compatibility, that could be implemented as an additional option `--pyxis-api-token-path`.

## Additional context.
If you're still accepting the contributors, I would be happy to work on the implementation.

### PR DESCRIPTION
**Pull request by tkrishtop**
Adding a recipe to fix #692

### CODE REVIEW

**Review by acornett21 — APPROVED** [review]

**Review by skattoju — APPROVED** [review]

**Comment by komish** [comment]
Weird, why do we _lose_ coverage here?

**Comment by tkrishtop** [comment]
> Weird, why do we lose coverage here?

@komish it seems to be a bug. Here is the [coverage report for the PR](https://coveralls.io/builds/51347932), it complains that two lines were added into cmd/root.go file. Since I didn't change that file, does it look like some automated formatting during the code coverage? A new line somewhere?

**Comment by tkrishtop** [comment]
Hello team, the proposed config is tested, [here is the invocation and the results](https://www.distributed-ci.io/jobs/b8d1a446-cdc7-42cb-8d43-12850c559d25/jobStates#c32b1199-c4c8-42f1-8f93-eece4ba5fc15:file111). It seems like I don't have permissions to merge a PR, so please feel free to merge when it seems to be convenient for you.

**Pull request merged**
