### PR TITLE
Move to Operator-SDK 1.30.0 based on ubi8.8

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Comment by tkrishtop** [comment]
> @tkrishtop: Cannot trigger testing until a trusted user reviews the PR and leaves an /ok-to-test message.

Hello team, I was wondering if it would be possible for me to become a trusted user to run the tests during the nighttime in your timezone?

**Comment by acornett21** [comment]
> > @tkrishtop: Cannot trigger testing until a trusted user reviews the PR and leaves an /ok-to-test message.
> 
> Hello team, I was wondering if it would be possible for me to become a trusted user to run the tests during the nighttime in your timezone?

Hi @tkrishtop, we started working in a different model for PR's based on recommendations from the OpenShift org to start using `Draft` pull requests. This ensures prow tests are not triggered until _after_ a PR has been reviewed, reworked and approved by the team. This workflow is recommend since the clusters we are using cost money, and we really only need the prow tests to run one time, not on each commit to a PR for example. Even if you were a trusted member, we wouldn't want these tests running without the PR in an approved state. Hopefully this makes sense, let us know if you have any questions. Thanks for all the PR's you raise, we do really appreciate the work.

**Review by acornett21 — APPROVED** [review]

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
